[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.9"
itertools = "0.13.0"
rayon = "1.7"
nalgebra = "0.32"
rand = "0.8.5"
indexmap = "2.7"
memoize = "0.4.2"
z3 = "0.12.1"
